name: Run release

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

permissions:
  contents: write

jobs:
  call:
    uses: chick-p/github-actions-shared-workflow/.github/workflows/release-npm-package-auto.yml@main
