name: Run Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call:
    uses: chick-p/github-actions-shared-workflow/.github/workflows/run-npm-script.yml@main
    with:
      script_name: "test"
