name: Run Test

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
      - name: Run lint
        run: |
          npm run test
